version: "3.7"

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: apache-php82
    volumes:
      - /var/www/laravel10-basic.test:/var/www
    ports:
      - "80:80"
    networks:
      - desenvolvimento
  db:
    image: mysql:8.1
    container_name: mysql81
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teste
    ports:
      - 1722:3306
    volumes:
      - mysql81:/var/lib/mysql
    networks:
      - desenvolvimento
    tty: true
networks:
  desenvolvimento:
    driver: bridge
volumes:
  mysql81:
